### ISSUE TITLE
请问怎么用？

### ISSUE THREAD

**Issue by silas6012** [adhu2018/xapkInstaller#2]
Release的是exe文件，在windows上用的？我想在小米手机上装xapk，怎么用这个工具？谢谢。

**Comment by adhu2018** [comment]
> Release的是exe文件，在windows上用的？我想在小米手机上装xapk，怎么用这个工具？谢谢。

的确是在windows上用的，我的原始需求只是在不关闭miui优化的同时，给小米手机安装xapk。
在readme中根据需要安装的文件类型下载配置对应的文件，打开手机的usb调试，通过usb或者其他方式连接电脑，选中xapk文件右键选择使用xapkinstaller打开就行
（好像直接在qq邮箱回复有问题？？）

**Comment by silas6012** [comment]
明白了，我也是不想关闭优化看能否安装。我连电脑试试看，如有问题再请教。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "adhu2018/xapkInstaller"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月14日(星期四) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [adhu2018/xapkInstaller] 请问怎么用？ (#2)





  
Release的是exe文件，在windows上用的？我想在小米手机上装xapk，怎么用这个工具？谢谢。
  
的确是在windows上用的，我的原始需求只是在不关闭miui优化的同时，给小米手机安装xapk。
 在readme中根据需要安装的文件类型下载配置对应的文件，打开手机的usb调试，通过usb或者其他方式连接电脑，选中xapk文件右键选择使用xapkinstaller打开就行
 （好像直接在qq邮箱回复有问题？？）
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by adhu2018** [comment]
如果不想进一步配置adb的话，直接解压，然后把xapkinstaller4win.exe放到adb.exe的相同目录下就行。xapkinstaller是单文件执行的，不需要安装

**Comment by adhu2018** [comment]
用邮箱发有问题的，要在github这里发
