### ISSUE TITLE
TypeError: install_xapk() missing 1 required positional argument: 'abc'

### ISSUE THREAD

**Issue by yazhuodong-wyze** [adhu2018/xapkInstaller#4]
正在复制 `a.xapk` 到 `C:\Users\dongy\Downloads\platform-tools\0cc175b9c0f1b6a831c399e269772661.xapk`
adb devices
文件越大，解压越慢，请耐心等待...
Traceback (most recent call last):
  File "xapkInstaller.py", line 578, in main
TypeError: install_xapk() missing 1 required positional argument: 'abc'
删除    C:\Users\dongy\Downloads\platform-tools\0cc175b9c0f1b6a831c399e269772661.xapk
删除    C:\Users\dongy\Downloads\platform-tools\0cc175b9c0f1b6a831c399e269772661
共1个，成功安装了0个。
按回车键继续...

**Comment by adhu2018** [comment]
到 https://github.com/adhu2018/xapkInstaller/actions 下最新生成的试试

**Comment by yazhuodong-wyze** [comment]
![image](https://user-images.githubusercontent.com/106308779/178503024-6fd046fd-fde8-47fe-a174-e77ee6d9371f.png)

**Comment by adhu2018** [comment]
是什么设备啊

**Comment by adhu2018** [comment]
好，按道理来说，android12不应该有这个问题啊

**Comment by adhu2018** [comment]
把备用的方案开了，可以帮忙测试一下吗，就最新发行版

**Comment by yazhuodong-wyze** [comment]
谢谢，你测试了吗？我刚看到信息。不好意思。没测的话，我看一下。

**Comment by adhu2018** [comment]
我不能复现这个问题

**Comment by yazhuodong-wyze** [comment]
ok，我重新安装一下试试。

**Comment by yazhuodong-wyze** [comment]
可能到晚上才能重新测，我上班用的mac。
